Add ToA tracking + minor fixes (v1.5)
Raitab/raid-data-tracker pull request #2
Opened 2024-08-07 18:36 UTC by null-zero

### v1.5
- Added Tombs of Amascut to the plugin
  - A massive thank you to [@LLemonDuck](https://github.com/LlemonDuck)
    - Implements [Tombs of Amascut](https://github.com/LlemonDuck/tombs-of-amascut) point tracking for personal ToA points
    - Implements Tombs of Amascut custom events for more accurate team point tracking when config "Send to External Plugins" setting is enabled on the ToA plugin.
  - Loot tracking
  - Split tracking
  - Custom Raid Level filter + single saveable preset slot
- Fixed test dependencies
- Loot prices now properly fetch from the G.E. before being written to the log
- Fixed bug where the UI panel would not refresh after a config change
- Properly removed dey0 time tracking that was missed in v1.4.4

// TODO
Fix and update client.getUsername() calls to account hashes

2024-08-21 03:28 UTC, Raitab requested changes
Hey ndot, so overall it looks good. Most of the things here are nits, like long lines, variable names or regex simplifications. I also know some of those things were copying what other parts of the code did, so don't feel too pressured to change those.

I can't make too many points about the functionality of code. I haven't worked with some of it, like the events, panels, and well, the actual ToA code, and I trust that you've tested it yourself, so I'm not concerned about functionality. Of course, that mostly just leaves me with style nitpicks and whatnot. I did let you know that Cas's styles were in direct conflict with my own.

Some things I didn't make comments on were that you had inconsistent brace styles. I'd prefer 1tbs/K&R for new development over Allman, but there are even conflicting styles next to each other and those are the only ones I'd like to see fixed before a merge.

You also used real tabs in your code adjacent to the 4-space indents used in a lot of places (4-space is my preferred), but ultimately means some of your code is indented completely differently cross-platform since I think github uses width-10 tabs so they're _really_ off. I'd like to see that cleaned up a bit.

We can discuss changes in Discord if you have objections or want to avoid changing things.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/toapointstracker/util/RaidStateTracker.java
> +	private static final int WIDGET_CHILD_ID = 40;
What widgets are these exactly?

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/SplitChanger.java
> +			default:
At the point you have a switch statement with the only three options being present, I'd remove the default clause or have the default log an error or return an empty list -- return the CoX uniques in the COX section.
If the selected raid tab is not part of one of the three (somehow), I'd rather it be empty than have CoX Uniques.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +	private final HashMap<String, RaidTracker> toaUUIDMap = new LinkedHashMap<>();
For all of these, I hadn't fixed them before, but you should camel case all initialisms, you're already doing it for cox/tob/toa within the words.
coxRtList, coxUuidMap.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidUniques.java
> +	SHADOW("Tumeken's shadow (uncharged)", ItemID.TUMEKENS_SHADOW),
I'd rename this to TUMEKENS_SHADOW to be in line with other drops in ToA. I'd probably make changes to the other enum names from other raids, too, but that's not part of the review.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/toapointstracker/util/RaidMode.java
> +	;
Dangling enum semicolon.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/toapointstracker/util/RaidRoom.java
> +	;
Dangling enum semicolon.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/toapointstracker/util/RaidRoom.java
> +		;
Dangling enum semicolon.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +    public RaidTrackerPanel(final ItemManager itemManager, FileReadWriter fw, RaidTrackerConfig config, ClientThread clientThread, Client client, ConfigManager configManager, PluginManager pluginMana
Line is too long.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +		} else
Move the brace up to this line.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +		if (isToAInstalled)
Move the brace up to this line

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				break;
These lines are too long.
Sometimes there are spaces after breaks, is that intentional?

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				default:
Repeating what I've said elsewhere that COX should be an expectation, not a default. Omit the default, return empty data, or error if we somehow are in the wrong area.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				teamSize = new JComboBox<>(new String []{"All sizes", "Solo", "Duo", "Trio", "4-man", "5-man", "6-man", "7-man", "8-10 Players", "11-14 Players", "15-24 Players", "24+ Players"});
break this line

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +			default:
Repeating again, omit default, return empty data, or error if we end up in this scenario unexpectedly.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +			final int saveInput = JOptionPane.showConfirmDialog(this.getRootPane(), "<html>Are you sure you want to save this Custom filter preset? It will overwrite your previous Custom filter values.<br/>Th
break this line

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +			public void mouseExited (java.awt.event.MouseEvent e){
This shouldn't be the full package name, should also be updated in the other places in this file.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +		filterFieldLow.putClientProperty( "JTextField.selectAllOnFocusPolicy", "never" );
extra spaces

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				if (!Pattern.matches("-?[0-9]+", userInput))
\d instead of [0-9]

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				if (!Pattern.matches("-?[0-9]+", userInput)) {
\d instead of [0-9]

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				if (Integer.parseInt(userInput) > 600) {
The 600s here come off as magic numbers. They should be replaced with a constant.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				case TOA:
break these long lines

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				default:
Broken record yadda yadda, expect CoX, don't default to CoX.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +				wrapper.add(timeTable);
Long lines

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +//				}
Is this commented code useful?

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +					tempRTList = tobRTList.stream().filter(RT -> !RT.isMvpInOwnName())
lowercase rt
I know it's like that in other places.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +			default:
Expect CoX, don't default to CoX.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +			default:
Expect CoX, don't default to CoX.

2024-08-21 03:28 UTC, Raitab commented on src/test/java/com/raidtracker/RaidTrackerTest.java
> +
Long lines

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/filereadwriter/FileReadWriter.java
> +//				gson.toJson(lootList, new TypeToken<List<RaidTrackerItem>>(){}.getType())); //[null], raidtrackerplugin is added to the list of types, which is automatically set to skipserialize true -> null r
Commented out code.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/filereadwriter/FileReadWriter.java
> +			default:
Expect CoX, don't default to CoX.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/RaidTrackerPlugin.java
> +	private static final Pattern TOA_COMPLETION_PATTERN = Pattern.compile(".*Tombs of Amascut: (.*) Mode (total|challenge) completion time:.*?([0-9]+:[.0-9]+)\\..*");
\d instead of [0-9] where applicable.

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/RaidTrackerPlugin.java
> +			if (!Objects.equals(Objects.requireNonNull(client.getWidget(WIDGET_TIMER)).getText(), "00:00") && !Objects.equals(Objects.requireNonNull(client.getWidget(WIDGET_TIMER)).getText(), "0:00.00") && !r
long line

2024-08-21 03:28 UTC, Raitab commented on src/main/java/com/raidtracker/RaidTrackerPlugin.java
> +		int WIDGET_TIMER = WidgetUtil.packComponentId(481, 46);
Magic numbers

2024-08-21 09:56 UTC, null-zero commented
I'll get to styling and these changes in the next few days. I also prefer 4 spaces and 1tbs. I'm pretty fresh to Java and completely forgot to change the styling settings in IntelliJ. Some of the code was also pulled from examples which would explain some of the weird formatting.

2024-08-21 10:18 UTC, null-zero commented on src/main/java/com/raidtracker/toapointstracker/util/RaidStateTracker.java
> +	private static final int WIDGET_CHILD_ID = 40;
This code is LlemonDuck's, but taking a look at the widget inspector shows that WIDGET_PARENT_ID is the canvas that the ToA raid and party widgets get drawn to. WIDGET_CHILD_ID is the ToA raid widget in particular (raid level, timer, and path levels, while excluding the party widget).

WIDGET_CHILD_ID :
![image](https://github.com/user-attachments/assets/95e36f4e-00fa-49e3-8f6a-43488341d001)

2024-10-23 18:47 UTC, null-zero commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +					tempRTList = tobRTList.stream().filter(RT -> !RT.isMvpInOwnName())
I'm not entirely sure I understand what you meant by this, unless you meant that "RaidTracker" in the `.filter(RaidTracker::isMvpInOwnName)` should be lowercase.

The reason its uppercase is that the filter is using a method reference of the RaidTracker class, while the lowercase "raidTracker" used elsewhere is the current RaidTracker object. I can change the code away from using a method reference if you'd like.

2024-10-23 18:47 UTC, null-zero commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +//				}
It was my first iteration of the filter, it isn't useful at this point of time and will be removed

2024-10-23 19:10 UTC, null-zero commented on src/main/java/com/raidtracker/ui/RaidTrackerPanel.java
> +					tempRTList = tobRTList.stream().filter(RT -> !RT.isMvpInOwnName())
Looking back at your other comments, I see the comment about using camel case for initialisms. With that in mind, I assume you meant that you wanted all "RT" instances lowercase?

2024-11-05 10:28 UTC, Raitab approved these changes
Thanks for your effort on this!

2024-11-05 10:30 UTC, merged